# Config file for an example Majora's Mask: Recompiled mod.

# Fields that end up in the mod's manifest.
[manifest]

# Unique ID of this mod. Pick something long enough that it'll never be the same as any other mod.
# The name displayed in the mod management menu is separate from this so this doesn't need to be human readable.
id = "mm_3ds_gibdo_trade"

# Version of this mod.
version = "1.0.0"

# The name that will show up for this mod in the mod menu. This should be human readable.
display_name = "3DS Gibdo Trade"

# The description that will show up when this mod is displayed in the mod menu. This should be human readable.
description =  """Replace the N64 trade by the 3DS one"""

# A short description that will show up in this mod's entry in the mod list. This should be human readable and kept short
# to prevent it from being cut off due to the limited space.
short_description = "3DS Gibdo trades!"

# Authors of this mod.
authors = [ "Eppe" ]

# ID of the target recomp game.
game_id = "mm"

# Minimum version of the target recomp (e.g. Zelda 64: Recompiled) that this mod can run on.
minimum_recomp_version = "1.2.0"

# Dependency mods. Each entry is the mod's ID and then an optional minimum version of the dependency mod.
dependencies = ["MM_EZ_Text_Replacer_API:2.3.0"]

# Native libraries (e.g. DLLs) and the functions they export.
native_libraries = [
# Example native library:
#    { name = "my_native_library", funcs = ["my_native_library_function"] }
]

# Inputs to the mod tool.
[inputs]

# Input elf file to generate a mod from.
elf_path = "build/mod.elf"

# Output mod filename.
mod_filename = "mm_3ds_gibdo_trade"

# Reference symbol files.
func_reference_syms_file = "Zelda64RecompSyms/mm.us.rev1.syms.toml"
data_reference_syms_files = [ "Zelda64RecompSyms/mm.us.rev1.datasyms.toml", "Zelda64RecompSyms/mm.us.rev1.datasyms_static.toml","static_symbols.toml" ]

# Additional files to include in the mod.
additional_files = ["thumb.png"]
# Config options.

[[manifest.config_options]]
id = "custom_potion_gibdo"
name = "Gibdo Potion Trade"
description = """Change the potion trade of the first gibdo.
Note: Reload the room that you're in to have the change take
place. 
Warning: If you play in Randomizer, playing with the "Red potion"
option will put you out of logic since you don't always have
access to the blue potion before the red one.
"""
type = "Enum"
options = [
    "Red Potion",
    "Blue Potion",
]
default = "Red Potion"